user_login:
    path: /login
    defaults: { _controller: CoreBundle:User:login }
    
login_check:
    path: /login_check
    defaults: { _controller: CoreBundle:User:login }


user_check:
    path: /check.htm
    defaults: { _controller: CoreBundle:User:loginCheck }    
    
    
logout:
    path: /logout.htm
    defaults: { _controller: CoreBundle:User:logout }  
          

    
  
