services:
    poznet.twig_extension:
        class: Poznet\CoreBundle\Twig\Extension\FileExistsExtension
        tags:
            - { name: twig.extension }
    
    konfig:
        class: Poznet\CoreBundle\Services\Konfig
        arguments:    ["@kernel"]
    
    log:
        class: Poznet\CoreBundle\Services\Log
        arguments:  ["@doctrine.orm.entity_manager","@security.token_storage"]
        
    pozet.mediacontainer:
        class: Poznet\CoreBundle\Services\MediaContainer
        arguments:  ["@AppKernel"]
