services:
    poznet.twig_extension:
        class: Poznet\CoreBundle\Twig\Extension\FileExistsExtension
        tags:
            - { name: twig.extension }
    
    konfig:
        class: Poznet\CoreBundle\Services\Konfig
        arguments:    ["@kernel"]